language: node_js
node_js: 8

matrix:
  include:
    - language: objective-c
      os: osx
      osx_image: xcode9.3
      env:
        - REACT_NATIVE_VERSION=0.53.3
        - PATH=$PATH:~/Library/Python/2.7/bin
      install:
        - ./scripts/install.ios.sh
      script:
        - ./scripts/ci.ios.sh
        - ./scripts/upload_artifact.sh
    - language: objective-c
      os: osx
      osx_image: xcode9.3
      env:
        - REACT_NATIVE_VERSION=0.51.1
        - PATH=$PATH:~/Library/Python/2.7/bin
      install:
        - ./scripts/install.ios.sh
      script:
        - ./scripts/ci.ios.sh
        - ./scripts/upload_artifact.sh
    - language: android
      os: linux
      jdk: oraclejdk8
      env:
        - REACT_NATIVE_VERSION=0.51.1
      android:
        components:
          - build-tools-27.0.2
          - build-tools-26.0.2
          - android-27
          - extra-android-m2repository
          - extra-google-google_play_services
          - extra-google-m2repository
          - sys-img-armeabi-v7a-android-27
      install:
      - ./scripts/install.android.sh
      script:
      - ./scripts/ci.android.sh
    # Example Projects
    - language: objective-c
      os: osx
      osx_image: xcode9.3
      env:
        - REACT_NATIVE_VERSION=0.51.1
      install:
      - ./scripts/install.ios.sh
      script:
      - ./scripts/demo-projects.ios.sh

    # Website
    - language: node_js
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libstdc++-4.9-dev
      env:
        - NAME='Website - master'
      node_js: 8
      script:
      - scripts/publish-website.sh

branches:
  only:
  - master
before_install:
  - nvm install 8
  - pip install awscli --upgrade --user
